/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Poncho
 */
public class Control_Prenatal extends javax.swing.JFrame {

    private int xMouse, yMouse, contador = 0;
    private Byte riesgo, acido, sulfato, ttd, tdpa, influenza;
    private DataBase bd;
    private String nombre;
    private byte[] arreglo = new byte[6];
    private boolean[] arreglo2 = new boolean[6];
    private JRadioButton[] radios;
    private ButtonGroup[] grupos;
    private boolean a, ac, s, tt, td, i;
    private String diagnostico, medicoTratante, fecha;
    private int id;
    private boolean existe;
    private int[] index;
    private String[] datos;
    private boolean[] unoCero;

    /**
     * Creates new form Control_Prenatal
     */
    public Control_Prenatal() {
        initComponents();
        radios = new JRadioButton[]{jrbalto, jrbbajo, jrbalto1, jrbbajo1, jrbalto2, jrbbajo2, jrbalto3, jrbbajo3, jrbalto4, jrbbajo4, jrbalto5, jrbbajo5};

        bd = new DataBase();

        jbgriesgo.add(jrbalto);
        jbgriesgo.add(jrbbajo);

        jbgacido.add(jrbalto1);
        jbgacido.add(jrbbajo1);

        jbgsulfato.add(jrbalto2);
        jbgsulfato.add(jrbbajo2);

        jbgttd.add(jrbalto3);
        jbgttd.add(jrbbajo3);

        jbgtdpa.add(jrbalto4);
        jbgtdpa.add(jrbbajo4);

        buttonGroup4.add(jrbalto5);
        buttonGroup4.add(jrbbajo5);

    }

    public Control_Prenatal(int id, String medicoTratante, String diagnostico, String fecha) {
        initComponents();
        radios = new JRadioButton[]{jrbalto, jrbbajo, jrbalto1, jrbbajo1, jrbalto2, jrbbajo2, jrbalto3, jrbbajo3, jrbalto4, jrbbajo4, jrbalto5, jrbbajo5};

        bd = new DataBase();

        jbgriesgo.add(jrbalto);
        jbgriesgo.add(jrbbajo);

        jbgacido.add(jrbalto1);
        jbgacido.add(jrbbajo1);

        jbgsulfato.add(jrbalto2);
        jbgsulfato.add(jrbbajo2);

        jbgttd.add(jrbalto3);
        jbgttd.add(jrbbajo3);

        jbgtdpa.add(jrbalto4);
        jbgtdpa.add(jrbbajo4);

        buttonGroup4.add(jrbalto5);
        buttonGroup4.add(jrbbajo5);
        this.id = id;
        this.medicoTratante = medicoTratante;
        this.diagnostico = diagnostico;
        this.fecha = fecha;
        existe = true;
    }

    public Control_Prenatal(String[] datos, int[] index){
        initComponents();
        radios = new JRadioButton[]{jrbalto, jrbbajo, jrbalto1, jrbbajo1, jrbalto2, jrbbajo2, jrbalto3, jrbbajo3, jrbalto4, jrbbajo4, jrbalto5, jrbbajo5};

        bd = new DataBase();

        jbgriesgo.add(jrbalto);
        jbgriesgo.add(jrbbajo);

        jbgacido.add(jrbalto1);
        jbgacido.add(jrbbajo1);

        jbgsulfato.add(jrbalto2);
        jbgsulfato.add(jrbbajo2);

        jbgttd.add(jrbalto3);
        jbgttd.add(jrbbajo3);

        jbgtdpa.add(jrbalto4);
        jbgtdpa.add(jrbbajo4);

        buttonGroup4.add(jrbalto5);
        buttonGroup4.add(jrbbajo5);
        
        unoCero = new boolean[6];
        this.datos = datos;
        this.index = index;
        existe = false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgriesgo = new javax.swing.ButtonGroup();
        jbgacido = new javax.swing.ButtonGroup();
        jbgttd = new javax.swing.ButtonGroup();
        jbgtdpa = new javax.swing.ButtonGroup();
        jbgsulfato = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        equis = new javax.swing.JLabel();
        jpconsultar = new javax.swing.JPanel();
        jlbconsultar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jrbalto = new javax.swing.JRadioButton();
        jrbbajo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jrbalto1 = new javax.swing.JRadioButton();
        jrbbajo1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jrbalto2 = new javax.swing.JRadioButton();
        jrbbajo2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jrbalto3 = new javax.swing.JRadioButton();
        jrbbajo3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jrbalto4 = new javax.swing.JRadioButton();
        jrbbajo4 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jrbalto5 = new javax.swing.JRadioButton();
        jrbbajo5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        equis.setBackground(new java.awt.Color(102, 153, 255));
        equis.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        equis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equis.setText("x");
        equis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equis.setPreferredSize(new java.awt.Dimension(34, 34));
        equis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(equis, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        jpconsultar.setBackground(new java.awt.Color(51, 153, 255));
        jpconsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlbconsultar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jlbconsultar.setForeground(new java.awt.Color(255, 255, 255));
        jlbconsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbconsultar.setText("Siguiente");
        jlbconsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbconsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbconsultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbconsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbconsultarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbconsultarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpconsultarLayout = new javax.swing.GroupLayout(jpconsultar);
        jpconsultar.setLayout(jpconsultarLayout);
        jpconsultarLayout.setHorizontalGroup(
            jpconsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpconsultarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpconsultarLayout.setVerticalGroup(
            jpconsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpconsultarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(jpconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 140, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Control prenatal");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Cuenta con las siguientes vacunas?");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 230, 40));

        jrbalto.setText("Alto");
        jrbalto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbaltoActionPerformed(evt);
            }
        });
        background.add(jrbalto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jrbbajo.setText("Bajo");
        background.add(jrbbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel7.setText("Riesgo Obstetricas ");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        jrbalto1.setText("Si ");
        jrbalto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbalto1ActionPerformed(evt);
            }
        });
        background.add(jrbalto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jrbbajo1.setText("No");
        background.add(jrbbajo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("Se otorgo");
        background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 60, 30));

        jLabel9.setText("Sulfato Ferroso");
        background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 50));

        jrbalto2.setText("Si ");
        jrbalto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbalto2ActionPerformed(evt);
            }
        });
        background.add(jrbalto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jrbbajo2.setText("No");
        background.add(jrbbajo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel10.setText("Acido Folico");
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 30));

        jLabel11.setText("TTD");
        background.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 50));

        jrbalto3.setText("Si ");
        jrbalto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbalto3ActionPerformed(evt);
            }
        });
        background.add(jrbalto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jrbbajo3.setText("No");
        background.add(jrbbajo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel12.setText("TDAP");
        background.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 50));

        jrbalto4.setText("Si ");
        jrbalto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbalto4ActionPerformed(evt);
            }
        });
        background.add(jrbalto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jrbbajo4.setText("No");
        background.add(jrbbajo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jLabel13.setText("Influenza");
        background.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 50));

        jrbalto5.setText("Si ");
        jrbalto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbalto5ActionPerformed(evt);
            }
        });
        background.add(jrbalto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jrbbajo5.setText("No");
        background.add(jrbbajo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisMouseClicked
        System.exit(0);
    }//GEN-LAST:event_equisMouseClicked

    private void equisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisMouseEntered
        jPanel3.setBackground(Color.red);
        equis.setForeground(Color.white);
    }//GEN-LAST:event_equisMouseEntered

    private void equisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisMouseExited
        jPanel3.setBackground(new Color(153, 153, 255));
        equis.setForeground(Color.black);
    }//GEN-LAST:event_equisMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        this.setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jrbaltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbaltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbaltoActionPerformed

    private void jrbalto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbalto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbalto1ActionPerformed

    private void jrbalto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbalto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbalto2ActionPerformed

    private void jrbalto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbalto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbalto3ActionPerformed

    private void jrbalto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbalto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbalto4ActionPerformed

    private void jrbalto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbalto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbalto5ActionPerformed

    private void jlbconsultarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbconsultarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbconsultarMousePressed

    private void jlbconsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbconsultarMouseExited
        jpconsultar.setBackground(new Color(53, 153, 255));
        jlbconsultar.setForeground(Color.white);
    }//GEN-LAST:event_jlbconsultarMouseExited

    private void jlbconsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbconsultarMouseEntered
        jpconsultar.setBackground(Color.blue);
        jlbconsultar.setForeground(Color.black);
    }//GEN-LAST:event_jlbconsultarMouseEntered

    private void jlbconsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbconsultarMouseClicked

        if (jrbalto.isSelected()) {
            a = true;
            riesgo = 1;
            arreglo2[0] = true;
        } else if (jrbbajo.isSelected()) {
            riesgo = 0;
            a = true;
            arreglo2[0] = false;
        } else {
            riesgo = 10;
            a = false;
        }

        if (jrbalto1.isSelected()) {
            ac = true;
            acido = 1;
            arreglo2[1] = true;
        } else if (jrbbajo1.isSelected()) {
            acido = 0;
            ac = true;
            arreglo2[1] = false;
        } else {
            acido = 10;
            ac = false;
        }

        if (jrbalto2.isSelected()) {
            s = true;
            sulfato = 1;
            arreglo2[2] = true;
        } else if (jrbbajo2.isSelected()) {
            sulfato = 0;
            s = true;
            arreglo2[2] = false;
        } else {
            sulfato = 10;
            a = false;
        }

        if (jrbalto3.isSelected()) {
            tt = true;
            ttd = 1;
            arreglo2[3] = true;
        } else if (jrbbajo3.isSelected()) {
            ttd = 0;
            tt = true;
            arreglo2[3] = false;
        } else {
            tt = false;
            ttd = 10;
        }

        if (jrbalto4.isSelected()) {
            td = true;
            tdpa = 1;
            arreglo2[4] = true;
        } else if (jrbbajo4.isSelected()) {
            tdpa = 0;
            td = true;
            arreglo2[4] = false;
        } else {
            tdpa = 10;
            td = false;
        }

        if (jrbalto5.isSelected()) {
            influenza = 1;
            i = true;
            arreglo2[5] = true;
        } else if (jrbbajo5.isSelected()) {
            influenza = 0;
            i = true;
            arreglo2[5] = false;
        } else {
            influenza = 10;
            i = false;
        }

        arreglo[0] = riesgo;
        arreglo[1] = acido;
        arreglo[2] = sulfato;
        arreglo[3] = ttd;
        arreglo[4] = tdpa;
        arreglo[5] = influenza;

        for (int i = 0; i < arreglo.length; i++) {
            if (arreglo[i] == 10) {
                contador++;
            }
        }
        if (existe) {
            if (a == true && ac == true && s == true && tt == true && td == true && i == true) {
                System.out.println(id + medicoTratante + diagnostico + fecha);
                bd.actualizarConsulta(id, medicoTratante, diagnostico, fecha, arreglo2);
                JOptionPane.showMessageDialog(this, "Tus datos han sido ingresados correctamente");

            } else {
                JOptionPane.showMessageDialog(this, "Te falta llenar " + contador + " campos");
                contador = 0;
            }
        } else {
            if (a == true && ac == true && s == true && tt == true && td == true && i == true) {
                for (int i=0; i<unoCero.length; i++){
                    unoCero[i] = arreglo2[i];
                }
                bd.registrarConsulta(datos, index, unoCero);
                JOptionPane.showMessageDialog(this, "Tus datos han sido ingresados correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Te falta llenar " + contador + " campos");
                contador = 0;
            }
        }
    }//GEN-LAST:event_jlbconsultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Control_Prenatal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Control_Prenatal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Control_Prenatal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Control_Prenatal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Control_Prenatal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel equis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup jbgacido;
    private javax.swing.ButtonGroup jbgriesgo;
    private javax.swing.ButtonGroup jbgsulfato;
    private javax.swing.ButtonGroup jbgtdpa;
    private javax.swing.ButtonGroup jbgttd;
    private javax.swing.JLabel jlbconsultar;
    private javax.swing.JPanel jpconsultar;
    private javax.swing.JRadioButton jrbalto;
    private javax.swing.JRadioButton jrbalto1;
    private javax.swing.JRadioButton jrbalto2;
    private javax.swing.JRadioButton jrbalto3;
    private javax.swing.JRadioButton jrbalto4;
    private javax.swing.JRadioButton jrbalto5;
    private javax.swing.JRadioButton jrbbajo;
    private javax.swing.JRadioButton jrbbajo1;
    private javax.swing.JRadioButton jrbbajo2;
    private javax.swing.JRadioButton jrbbajo3;
    private javax.swing.JRadioButton jrbbajo4;
    private javax.swing.JRadioButton jrbbajo5;
    // End of variables declaration//GEN-END:variables
}
