/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Poncho
 */
public class Diagnostico extends javax.swing.JFrame {

    private int xMouse, yMouse;
    private String medicoTratante;
    private DataBase bd;
    private Control_Prenatal cp;
    private int id, item;
    private String fecha;
    private boolean existe;
    private String[] datos;
    private int[] index;

    /**
     * Creates new form Diagnostico
     */
    public Diagnostico() {
        initComponents();
    }

    public Diagnostico(int id, String medicoTratante, String nombre) {
        initComponents();
        this.id = id;
        bd = new DataBase();
        this.medicoTratante = medicoTratante;
        jlbdiag.setText(nombre);
        fecha = bd.ConsultaFecha(id);
        jtfecha.setText(fecha);
        bd.desconectar();
        existe = true;
    }

    public Diagnostico(String[] datos, int[] index) {
        initComponents();
        item = datos.length;
        this.index = index;
        this.datos = new String[datos.length + 1];
        for (int i = 0; i < datos.length; i++) {
            this.datos[i] = datos[i];
        }
        existe = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        equis = new javax.swing.JLabel();
        jlbdiag = new javax.swing.JLabel();
        jpconsultar = new javax.swing.JPanel();
        jlbconsultar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfnuevafecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtadiagnostico = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfecha = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        equis.setBackground(new java.awt.Color(102, 153, 255));
        equis.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        equis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equis.setText("x");
        equis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equis.setPreferredSize(new java.awt.Dimension(34, 34));
        equis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(equis, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 40));

        jlbdiag.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        background.add(jlbdiag, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 310, 40));

        jpconsultar.setBackground(new java.awt.Color(51, 153, 255));
        jpconsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlbconsultar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jlbconsultar.setForeground(new java.awt.Color(255, 255, 255));
        jlbconsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbconsultar.setText("Siguiente");
        jlbconsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbconsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbconsultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbconsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbconsultarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbconsultarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpconsultarLayout = new javax.swing.GroupLayout(jpconsultar);
        jpconsultar.setLayout(jpconsultarLayout);
        jpconsultarLayout.setHorizontalGroup(
            jpconsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpconsultarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpconsultarLayout.setVerticalGroup(
            jpconsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpconsultarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(jpconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 140, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Por favor ingresa el diagnostico de la paciente");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nueva Fecha");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 140, 30));

        jtfnuevafecha.setBorder(null);
        jtfnuevafecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnuevafechaActionPerformed(evt);
            }
        });
        background.add(jtfnuevafecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 180, 20));

        jtadiagnostico.setColumns(20);
        jtadiagnostico.setRows(5);
        jScrollPane1.setViewportView(jtadiagnostico);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 390, 180));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("fecha de parto?");
        background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 130, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Fecha anterior");
        background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 140, 20));

        jtfecha.setBorder(null);
        jtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfechaActionPerformed(evt);
            }
        });
        background.add(jtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, 20));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 507, 190, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("¿Desea hacer una modificacion de la posible");
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 360, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisMouseClicked
        System.exit(0);
    }//GEN-LAST:event_equisMouseClicked

    private void equisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisMouseEntered
        jPanel3.setBackground(Color.red);
        equis.setForeground(Color.white);
    }//GEN-LAST:event_equisMouseEntered

    private void equisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisMouseExited
        jPanel3.setBackground(new Color(153, 153, 255));
        equis.setForeground(Color.black);
    }//GEN-LAST:event_equisMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        this.setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jlbconsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbconsultarMouseClicked
        System.out.println(existe);
        if (existe) {
            if (!jtfnuevafecha.getText().equals("")) {
                fecha = jtfnuevafecha.getText();
                

            }
            if (!jtadiagnostico.getText().equals("")) {
                Control_Prenatal cp = new Control_Prenatal(id, medicoTratante, jtadiagnostico.getText(), jtfnuevafecha.getText());
                cp.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "No ha llenado el diagnostico");
            }
        } else {
            if (!jtfnuevafecha.getText().equals("")) {
                datos[17] = jtfnuevafecha.getText();
               

            }
            if (!jtadiagnostico.getText().equals("")) {
                datos[item] = jtadiagnostico.getText();
                Control_Prenatal cp = new Control_Prenatal(datos, index);
                cp.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "No ha llenado el diagnostico");
            }
        }
    }//GEN-LAST:event_jlbconsultarMouseClicked

    private void jlbconsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbconsultarMouseEntered
        jpconsultar.setBackground(Color.blue);
        jlbconsultar.setForeground(Color.black);
    }//GEN-LAST:event_jlbconsultarMouseEntered

    private void jlbconsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbconsultarMouseExited
        jpconsultar.setBackground(new Color(53, 153, 255));
        jlbconsultar.setForeground(Color.white);
    }//GEN-LAST:event_jlbconsultarMouseExited

    private void jlbconsultarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbconsultarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbconsultarMousePressed

    private void jtfnuevafechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnuevafechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnuevafechaActionPerformed

    private void jtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnostico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel equis;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlbconsultar;
    private javax.swing.JLabel jlbdiag;
    private javax.swing.JPanel jpconsultar;
    private javax.swing.JTextArea jtadiagnostico;
    private javax.swing.JTextField jtfecha;
    private javax.swing.JTextField jtfnuevafecha;
    // End of variables declaration//GEN-END:variables
}
