/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author mike
 */
public class MostrarPacientes extends javax.swing.JFrame {

    DataBase db;
    DefaultTableModel modelo;

    public MostrarPacientes() {
        initComponents();
        setLocationRelativeTo(null);
        db = new DataBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        panelEquis = new javax.swing.JPanel();
        labelEquis = new javax.swing.JLabel();
        panelPuerperas = new javax.swing.JPanel();
        labelPuerperas = new javax.swing.JLabel();
        panelCenso = new javax.swing.JPanel();
        labelCenso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setBackground(new java.awt.Color(204, 204, 204));
        scroll.setViewportView(tabla);

        jPanel1.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 910, 440));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        panelEquis.setBackground(new java.awt.Color(102, 153, 255));
        panelEquis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelEquis.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelEquis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEquis.setText("x");
        labelEquis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEquis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEquisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEquisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEquisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEquisLayout = new javax.swing.GroupLayout(panelEquis);
        panelEquis.setLayout(panelEquisLayout);
        panelEquisLayout.setHorizontalGroup(
            panelEquisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEquis, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );
        panelEquisLayout.setVerticalGroup(
            panelEquisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquisLayout.createSequentialGroup()
                .addComponent(labelEquis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(874, Short.MAX_VALUE)
                .addComponent(panelEquis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelEquis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 50));

        panelPuerperas.setBackground(new java.awt.Color(51, 153, 255));

        labelPuerperas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelPuerperas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPuerperas.setText("Puerperas");
        labelPuerperas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPuerperasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelPuerperasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelPuerperasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelPuerperasLayout = new javax.swing.GroupLayout(panelPuerperas);
        panelPuerperas.setLayout(panelPuerperasLayout);
        panelPuerperasLayout.setHorizontalGroup(
            panelPuerperasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPuerperas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPuerperasLayout.setVerticalGroup(
            panelPuerperasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPuerperas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelPuerperas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, 30));

        panelCenso.setBackground(new java.awt.Color(51, 153, 255));

        labelCenso.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelCenso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCenso.setText("Censo Activo");
        labelCenso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCensoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCensoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCensoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCensoLayout = new javax.swing.GroupLayout(panelCenso);
        panelCenso.setLayout(panelCensoLayout);
        panelCensoLayout.setHorizontalGroup(
            panelCensoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCenso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCensoLayout.setVerticalGroup(
            panelCensoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCenso, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelCenso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelEquisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEquisMouseClicked
        labelEquis.setForeground(Color.black);
        panelEquis.setBackground(new Color(102,153,255));
        dispose();
    }//GEN-LAST:event_labelEquisMouseClicked

    private void labelEquisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEquisMouseEntered
        labelEquis.setForeground(Color.white);
        panelEquis.setBackground(Color.red);
    }//GEN-LAST:event_labelEquisMouseEntered

    private void labelEquisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEquisMouseExited
        labelEquis.setForeground(Color.black);
        panelEquis.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_labelEquisMouseExited

    private void labelCensoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCensoMouseEntered
        panelCenso.setBackground(Color.blue);
        labelCenso.setForeground(Color.white);
    }//GEN-LAST:event_labelCensoMouseEntered

    private void labelCensoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCensoMouseExited
        panelCenso.setBackground(new Color(51,153,255));
        labelCenso.setForeground(Color.black);
    }//GEN-LAST:event_labelCensoMouseExited

    private void labelPuerperasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPuerperasMouseEntered
        panelPuerperas.setBackground(Color.blue);
        labelPuerperas.setForeground(Color.white);
    }//GEN-LAST:event_labelPuerperasMouseEntered

    private void labelPuerperasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPuerperasMouseExited
        panelPuerperas.setBackground(new Color(51,153,255));
        labelPuerperas.setForeground(Color.black);
    }//GEN-LAST:event_labelPuerperasMouseExited

    private void labelCensoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCensoMouseClicked
        modelo = db.censo();
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabla.setModel(modelo);
        int[] anchos = {22,120,132,86,83,95,97,98,68,36,61,55,50,61,60,45,38,55,102,97,86,84,116,35,36,56,72,61,58,201,276,74,93,107,77,92,76,86,100,109,178,141,110};
        for (int i = 0; i < 43; i++) {
            tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        scroll.setViewportView(tabla);
    }//GEN-LAST:event_labelCensoMouseClicked

    private void labelPuerperasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPuerperasMouseClicked
        modelo = db.puerperas();
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabla.setModel(modelo);
        int[] anchos = {22,120,132,86,83,95,97,98,68,36,61,55,50,61,60,45,38,55,102,97,86,84,116,35,36,56,72,61,58,201,276,74,93,107,77,92,76,86,100,109,178,141,110};
        for (int i = 0; i < 43; i++) {
            tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        scroll.setViewportView(tabla);
    }//GEN-LAST:event_labelPuerperasMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCenso;
    private javax.swing.JLabel labelEquis;
    private javax.swing.JLabel labelPuerperas;
    private javax.swing.JPanel panelCenso;
    private javax.swing.JPanel panelEquis;
    private javax.swing.JPanel panelPuerperas;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
