/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author mike
 */
public class NuevaPaciente extends javax.swing.JFrame {

    String nombre, telefono, CURP;
    String[] datos;
    int edad;
    int[] index;
    DataBase db;

    /**
     * Creates new form NuevaPaciente
     */
    public NuevaPaciente() {
        initComponents();
        setLocationRelativeTo(null);
        nombre = "Regina Esteves Flores";
        telefono = "5618151447";
        CURP = "ESFR06";
        edad = 26;
        nombreLB.setText(nombre);
        curpLB.setText(CURP);
        edadLB.setText(String.valueOf(edad));
        db = new DataBase();
        String[] doctores = db.doctores();
        for (int i=0; i<doctores.length; i++){
            medicoCB.addItem(doctores[i]);
        }
        db.desconectar();
    }

    public NuevaPaciente(String nombre, String telefono, String CURP, int edad) {
        initComponents();
        setLocationRelativeTo(null);
        this.nombre = nombre;
        this.telefono = telefono;
        this.CURP = CURP;
        this.edad = edad;
        nombreLB.setText(nombre);
        curpLB.setText(CURP);
        edadLB.setText(String.valueOf(edad));
        db = new DataBase();
        String[] doctores = db.doctores();
        for (int i=0; i<doctores.length; i++){
            medicoCB.addItem(doctores[i]);
        }
        db.desconectar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelEquis = new javax.swing.JPanel();
        labelEquis = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreLB = new javax.swing.JLabel();
        curpLB = new javax.swing.JLabel();
        edadLB = new javax.swing.JLabel();
        jurisdiccionCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        coordinacionTF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        unidadTF = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        cluesTF = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        panelSiguiente = new javax.swing.JPanel();
        labelSiguiente = new javax.swing.JLabel();
        medicoCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        panelEquis.setBackground(new java.awt.Color(102, 153, 255));
        panelEquis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelEquis.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelEquis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEquis.setText("x");
        labelEquis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEquis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEquisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEquisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEquisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEquisLayout = new javax.swing.GroupLayout(panelEquis);
        panelEquis.setLayout(panelEquisLayout);
        panelEquisLayout.setHorizontalGroup(
            panelEquisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEquis, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );
        panelEquisLayout.setVerticalGroup(
            panelEquisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquisLayout.createSequentialGroup()
                .addComponent(labelEquis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NUEVA PACIENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(panelEquis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelEquis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Coordinación Municipal:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        nombreLB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombreLB.setText("*Nombre Completo*");
        jPanel1.add(nombreLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        curpLB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        curpLB.setText("*CURP*");
        jPanel1.add(curpLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        edadLB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        edadLB.setText("*Edad* años");
        jPanel1.add(edadLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jurisdiccionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATLACOMULCO", "IXTLAXUACA", "JILOTEPEC", "TENANGO DEL VALLE", "TOLUCA", "XONACATLÁN", "TEJUPILCO", "TENANCINGO", "VALLE DE BRAVO", "ATIZAPÁN", "CUAUTITLÁN", "NAUCALPAN", "TEOTIHUACAN", "TLALNEPANTLA", "ZUMPANGO", "AMECAMECA", "ECATEPEC", "NEZAHUALCÓYOTL", "TEXCOCO" }));
        jPanel1.add(jurisdiccionCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Jurisdicción Sanitaria;");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Médico tratante:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        coordinacionTF.setBorder(null);
        jPanel1.add(coordinacionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 190, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 190, -1));

        unidadTF.setBorder(null);
        jPanel1.add(unidadTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 190, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Unidad Médica:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        cluesTF.setBorder(null);
        jPanel1.add(cluesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 190, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 190, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("Clave CLUES:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        panelSiguiente.setBackground(new java.awt.Color(51, 153, 255));

        labelSiguiente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelSiguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSiguiente.setText("SIGUIENTE");
        labelSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSiguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSiguienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSiguienteLayout = new javax.swing.GroupLayout(panelSiguiente);
        panelSiguiente.setLayout(panelSiguienteLayout);
        panelSiguienteLayout.setHorizontalGroup(
            panelSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSiguienteLayout.setVerticalGroup(
            panelSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panelSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 120, 40));

        jPanel1.add(medicoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelEquisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEquisMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelEquisMouseClicked

    private void labelEquisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEquisMouseEntered
        labelEquis.setForeground(Color.white);
        panelEquis.setBackground(Color.red);
    }//GEN-LAST:event_labelEquisMouseEntered

    private void labelEquisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEquisMouseExited
        labelEquis.setForeground(Color.black);
        panelEquis.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_labelEquisMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        
    }//GEN-LAST:event_jPanel2MousePressed

    private void labelSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSiguienteMouseClicked
        int jurisdiccion = jurisdiccionCB.getSelectedIndex();
        String medicoTratante = String.valueOf(medicoCB.getSelectedItem()).trim();
        String coordinacionMunicipal = coordinacionTF.getText();
        String unidadMedica = unidadTF.getText();
        String claveClues = cluesTF.getText();
        if (!medicoTratante.equals("") && !coordinacionMunicipal.equals("") && !claveClues.equals("")){
            datos = new String[] {nombre, telefono, CURP, medicoTratante, coordinacionMunicipal, unidadMedica, claveClues};
            index = new int[] {edad, jurisdiccion};
            new Domicilio(datos, index).setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.");
        }
    }//GEN-LAST:event_labelSiguienteMouseClicked

    private void labelSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSiguienteMouseEntered
        panelSiguiente.setBackground(Color.blue);
        labelSiguiente.setForeground(Color.white);
    }//GEN-LAST:event_labelSiguienteMouseEntered

    private void labelSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSiguienteMouseExited
        panelSiguiente.setBackground(new Color(51,153,255));
        labelSiguiente.setForeground(Color.black);
    }//GEN-LAST:event_labelSiguienteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cluesTF;
    private javax.swing.JTextField coordinacionTF;
    private javax.swing.JLabel curpLB;
    private javax.swing.JLabel edadLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> jurisdiccionCB;
    private javax.swing.JLabel labelEquis;
    private javax.swing.JLabel labelSiguiente;
    private javax.swing.JComboBox<String> medicoCB;
    private javax.swing.JLabel nombreLB;
    private javax.swing.JPanel panelEquis;
    private javax.swing.JPanel panelSiguiente;
    private javax.swing.JTextField unidadTF;
    // End of variables declaration//GEN-END:variables
}
